# Generated by Django 5.1.3 on 2024-11-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('specialtys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional', verbose_name='Profesional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialtys.specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['name'],
            },
        ),
    ]
