# Generated by Django 5.1.3 on 2024-11-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_hora_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
