# Generated by Django 5.1.3 on 2024-11-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialtys', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('image', models.ImageField(upload_to='professionals', verbose_name='Imagen')),
                ('degree', models.CharField(max_length=100, verbose_name='Titulación')),
                ('resume', models.TextField(verbose_name='Curriculum')),
                ('specialty', models.ManyToManyField(to='specialtys.specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía Seguro')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
        ),
    ]
