# Generated by Django 5.1.3 on 2024-11-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional', verbose_name='Profesional'),
        ),
    ]
