# Generated by Django 5.1.3 on 2024-11-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_patient_professional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
